services:
  servico.autenticacao.api:
    build:
      context: .
      dockerfile: src/ServicoAutenticacao.Api/Dockerfile
    container_name: servico.autenticacao.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_ENVIRONMENT=Development
    ports:
      - "8083:8080"
    networks:
      - services-network-autenticacao

networks:
  services-network-autenticacao:
    name: services-network-autenticacao
